### PR TITLE
Get the bazel image from gcr.io/cloud-builders 

### PR DESCRIPTION
**Pull request by wallrj**
Fixes: #46

### CODE REVIEW

**Comment by irbekrm** [comment]
Looks good to me! I don't know if you want to merge this now to make testing easier or afterwards together with the SHA so adding a hold

/lgtm
/approve
/hold

**Comment by wallrj** [comment]
I tested this change while releasing cert-manager: https://github.com/jetstack/cert-manager/releases/tag/v1.6.0-alpha.0

**Pull request merged**
